"""personal labels

Revision ID: 5a808c35e726
Revises: 63b66e68187a
Create Date: 2022-04-03 13:00:04.290737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a808c35e726'
down_revision = '63b66e68187a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'label')
    # ### end Alembic commands ###
